# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', multiselectfield.db.fields.MultiSelectField(choices=[('JR', 'Jurassic Park'), ('SH', 'Shakespeare')], max_length=5)),
            ],
        ),
    ]
