# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainging_model_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='TrainingModel',
        ),
    ]
