# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_training_model_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_model',
            name='pub_date',
        ),
    ]
