# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_remove_training_model_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_model',
            name='directory',
            field=models.CharField(default='ui/save/jurassicPark', max_length=100),
            preserve_default=False,
        ),
    ]
