# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_training_model_directory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Training_Model',
            new_name='Training_Input',
        ),
        migrations.RenameField(
            model_name='training_input',
            old_name='training_model_name',
            new_name='training_input_name',
        ),
    ]
